version: 0.2

phases:
  install:
    commands:
      # install node 12
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    # install dependencies
    commands:
      - pwd
      - ls -l
      - cd apollo-server && npm i
      - cd ..
      - cd tvmaze-ang && npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd ..
artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: dist/tvmaze


